Matriz transposta, identidade e inversa

In [1]:
import numpy as np

In [2]:
#A transposição da Matriz implica converter as linhas em colunas...
A=np.array([[1,2,3],[4,5,6]])
la,ca=A.shape
At=np.zeros((ca,la))
for i in range(ca):
    for j in range(la):
        At[i,j]=A[j,i]
A,At

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1., 4.],
        [2., 5.],
        [3., 6.]]))

In [3]:
#com numpy
A.T, A.transpose()

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [4]:
#A matriz identidade é quadrada (número de linhas=número de colunas)
# é uma matriz com um para todos os elementos da diag principal e zero no restante
#é o elemento neutro da multiplicação, mostre em uma matrix 3x3
i3=np.identity(3)
M=np.array([[1,2,3],[3,5,2],[9,0,4]])
M,np.dot(i3,M)

(array([[1, 2, 3],
        [3, 5, 2],
        [9, 0, 4]]),
 array([[1., 2., 3.],
        [3., 5., 2.],
        [9., 0., 4.]]))

In [5]:
#Uma matriz M, nultiplicada pela sua inversa, resulta a matriz identidade
#Inverta a matriz [[6,2],[1,1]] e multiplique pela identidade para provar
M=np.array([[6,2],[1,1]])
Minv=np.linalg.inv(M)
Minv,np.dot(Minv,M)

(array([[ 0.25, -0.5 ],
        [-0.25,  1.5 ]]),
 array([[1.00000000e+00, 5.55111512e-17],
        [0.00000000e+00, 1.00000000e+00]]))

In [6]:
#Vamos resolver o sistema de equações lineares
# A+B=6
# 2A-B=0
M=np.array([[1,1],[2,-1]])
y=np.array([[6],[0]])
X=np.dot(np.linalg.inv(M),y)
X

array([[2.],
       [4.]])

In [7]:
#Inverta uma matriz 3x3 e verifique se uam é mesmo a inversa da outra.
M=np.array([[1,1,2],[2,-1,4],[4,-1,0]])
Minv=np.linalg.inv(M)
np.dot(M,Minv)

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])