Operações com Matrizes

In [1]:
import numpy as np

In [5]:
#Soma de Matrizes. Sendo matrizes de mesmas dimensões, a soma é dada pela soma elemento a elemento
#Assim se C=A+B, para cada elemento C(i,j)=A(i,j)+B(i,j)
A=np.array([[1,2],[2,3]])
B=np.array([[5,7],[0,1]])
C=np.zeros((2,2))
A,B

(array([[1, 2],
        [2, 3]]),
 array([[5, 7],
        [0, 1]]))

In [4]:
#Obtenha C=A+B
A.shape==B.shape

True

In [6]:
l,c=A.shape
for i in range(l):
    for j in range(c):
        C[i,j]=A[i,j]+B[i,j]
        
C      

array([[6., 9.],
       [2., 4.]])

In [7]:
#Agora com numpy
A+B

array([[6, 9],
       [2, 4]])

In [8]:
#No produto de um escalar por uma matriz, basta multiplicar cada elemento da matriz pelo escalar
#Faça 3*A
for i in range(l):
    for j in range(c):
        A[i,j]=3*A[i,j]
A

array([[3, 6],
       [6, 9]])

In [9]:
#Com numpy
6*B

array([[30, 42],
       [ 0,  6]])

In [11]:
#No produto de matrizes A*B, o número de colunas de A deve ser igual ao numéro de linhas de B. Assim,
#é possível multiplicar Uma matriz A(2x5) por uma B(5,6). Multiplicando uma Matriz A3x2 por uma B2x4 resultará 
#em uma matriz de dimensões 3x4. Cada elemento i,j da matriz resultante é o produto "escalar" da linha i da 
#primeira matriz pela coluna j da segunda
A=np.array([[1,2],[2,3],[6,1]])
B=np.array([[5,7,4],[0,1,9]])
la,ca=A.shape
lb,cb=B.shape
C=np.zeros((la,cb))
print(C.shape)
for i in range(la):
    for j in range(cb):
        for k in range(ca):
            C[i,j]+=A[i,k]*B[k,j]
A,B,C            

(3, 3)


(array([[1, 2],
        [2, 3],
        [6, 1]]),
 array([[5, 7, 4],
        [0, 1, 9]]),
 array([[ 5.,  9., 22.],
        [10., 17., 35.],
        [30., 43., 33.]]))

In [13]:
#Com numpy
np.dot(A,B)

array([[ 5,  9, 22],
       [10, 17, 35],
       [30, 43, 33]])