Aquecimento det e bases

In [1]:
import numpy as np

In [9]:
#Obtenha o determinante de M na mão e com numpy
M=np.array([[2,1,0],[3,2,7],[1,1,1]])
print(M)

[[2 1 0]
 [3 2 7]
 [1 1 1]]


(-6, -6.000000000000001)

In [11]:
#Mostre que o det A é zero sem calculá-lo
A=np.array([[2,1,3],[3,2,5],[1,1,2]])


True

In [12]:
#Resolva a equação matricialmente
#x+y+2z=8
#x-y=0
#x-z=0


array([2., 2., 2.])

In [18]:
#dada a base x,y (1,0) e (0,1) e a base nova x',y' (1,0) e (0,-1)
#1)obtenha a transformação da nova para a antiga (matriz NA com as colunas recebendo a base nova) e a teste
#2)obtenha a transformação da antiga para a nova (invertendo a matriz NA) e a test
NA=np.array([[1,0],[0,-1]])
print(NA)

#observe que a inversa foi a transposta..isso acontece em bases ortigonais (o produto interno entre os vetores é nulo). 
#No caso, são bases ortonormais..além de ortogonais, são de vetores unitários

[[ 1  0]
 [ 0 -1]]
[ 1 -1]
[[ 1.  0.]
 [-0. -1.]]
[ 1. -1.]


In [19]:
#pense no caso da matriz identidade... as colunas são vetores ortogonais, assim a inversa é a tranposta que é ela mesma!
#Teste


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])