Vamos testar propriedades dos espaços vetoriais

In [2]:
import numpy as np

In [6]:
u=np.array([1,1,1,1])
v=np.array([2,2,2,2])
w=np.array([5,5,5,5])

u + (v+w)= (u+v)+w 

In [7]:
u + (v+w),(u+v)+w

(array([8, 8, 8, 8]), array([8, 8, 8, 8]))

u+v=v+u

In [8]:
u+v,v+u

(array([3, 3, 3, 3]), array([3, 3, 3, 3]))

∃0 ∊ V, u+0=u

In [9]:
zero=np.zeros(len(u))
u+zero,u

(array([1., 1., 1., 1.]), array([1, 1, 1, 1]))

∀u ∊ V, ∃-u, u+(-u)=0

In [11]:
mu=-1*u
u+mu

array([0, 0, 0, 0])

α(β)u=(αβ)u


In [12]:
3.0*(4.0*u),(3.0*4.0)*u

(array([12., 12., 12., 12.]), array([12., 12., 12., 12.]))

(α+β)u= αu+ βu


In [13]:
(3+4)*u,3*u+4*u

(array([7, 7, 7, 7]), array([7, 7, 7, 7]))

α(u+v)= αu+ αv


In [14]:
3*(u+v),3*u+3*v

(array([9, 9, 9, 9]), array([9, 9, 9, 9]))

1u=u


In [15]:
1*u,u

(array([1, 1, 1, 1]), array([1, 1, 1, 1]))