Brincando com Vetores

In [2]:
import numpy as np

In [3]:
#criar função soma de vetores e comparar com numpy
def soma(v1,v2):
    v=np.zeros(len(v1))
    for i in range(len(v)):
        v[i]=v1[i]+v2[i]
    return v

In [4]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
soma(a,b)

array([3., 5., 7., 9.])

In [5]:
a+b

array([3, 5, 7, 9])

In [8]:
#criar função que recebe escalar e multiplica vetor
def multv(alpha,v):
    for i in range(len(v)):
        v[i]=alpha*(v[i])
    return v

In [9]:
multv(3,a)

array([ 3,  6,  9, 12])

In [10]:
3*a

array([ 9, 18, 27, 36])

In [13]:
#crie função que compara vetores
def compv(v1,v2):
    if len(v1)!=len(v2):return False
    for i in range(len(v1)):
        if v1[i]!=v2[i]:return False
    return True

In [14]:
compv(a,b)

False

In [15]:
compv(a,a)

True

In [19]:
np.array_equal(a,a)

True

In [20]:
np.array_equal(a,b)

False

In [21]:
#faça a função produto escalar e a compare com numpy
def pi(a,b):
    s=0.0
    for i in range(len(a)):
        s+=a[i]*b[i]
    return s

In [23]:
pi(a,b)

120.0

In [24]:
np.inner(a,b)

120